import { PrismaClient } from '../app/generated/prisma';
import { PrismaPg } from '@prisma/adapter-pg'
import 'dotenv/config'
import bcrypt from 'bcryptjs';

const connectionString = `${process.env.DATABASE_URL}`

const adapter = new PrismaPg({ connectionString })
const prisma = new PrismaClient({ adapter })

async function main() {
    console.log('🌱 Seeding database...');

    // Crear usuarios
    const hashedPasswordUser = await bcrypt.hash('user123', 10);
    const hashedPasswordAdmin = await bcrypt.hash('admin123', 10);

    const users = await Promise.all([
        prisma.user.upsert({
            where: { email: 'user@retrommerce.com' },
            update: {},
            create: {
                email: 'user@retrommerce.com',
                name: 'Usuario Demo',
                password: hashedPasswordUser,
                role: 'USER',
            },
        }),
        prisma.user.upsert({
            where: { email: 'admin@retrommerce.com' },
            update: {},
            create: {
                email: 'admin@retrommerce.com',
                name: 'Administrador',
                password: hashedPasswordAdmin,
                role: 'ADMIN',
            },
        }),
    ]);

    console.log(`✅ Created ${users.length} users`);

    // Crear categorías
    const categories = await Promise.all([
        prisma.category.upsert({
            where: { slug: 'computadoras' },
            update: {},
            create: {
                name: 'Computadoras',
                slug: 'computadoras',
                description: 'Computadoras completas de los 90s y 2000s',
            },
        }),
        prisma.category.upsert({
            where: { slug: 'procesadores' },
            update: {},
            create: {
                name: 'Procesadores',
                slug: 'procesadores',
                description: 'CPUs clásicos de Intel, AMD y Cyrix',
            },
        }),
        prisma.category.upsert({
            where: { slug: 'memorias-ram' },
            update: {},
            create: {
                name: 'Memorias RAM',
                slug: 'memorias-ram',
                description: 'Módulos SIMM, DIMM y SDRAM vintage',
            },
        }),
        prisma.category.upsert({
            where: { slug: 'monitores-crt' },
            update: {},
            create: {
                name: 'Monitores CRT',
                slug: 'monitores-crt',
                description: 'Monitores de tubo catódico clásicos',
            },
        }),
        prisma.category.upsert({
            where: { slug: 'tarjetas-graficas' },
            update: {},
            create: {
                name: 'Tarjetas Gráficas',
                slug: 'tarjetas-graficas',
                description: 'GPUs retro de 3dfx, Nvidia, ATI',
            },
        }),
        prisma.category.upsert({
            where: { slug: 'discos-duros' },
            update: {},
            create: {
                name: 'Discos Duros',
                slug: 'discos-duros',
                description: 'HDDs IDE y SCSI vintage',
            },
        }),
        prisma.category.upsert({
            where: { slug: 'perifericos' },
            update: {},
            create: {
                name: 'Periféricos',
                slug: 'perifericos',
                description: 'Teclados, ratones y otros periféricos retro',
            },
        }),
        prisma.category.upsert({
            where: { slug: 'tarjetas-sonido' },
            update: {},
            create: {
                name: 'Tarjetas de Sonido',
                slug: 'tarjetas-sonido',
                description: 'Sound Blaster y otras tarjetas de audio clásicas',
            },
        }),
    ]);

    console.log(`✅ Created ${categories.length} categories`);

    // Crear productos de ejemplo
    const products = await Promise.all([
        // === COMPUTADORAS ===
        prisma.product.upsert({
            where: { slug: 'ibm-thinkpad-600e' },
            update: {},
            create: {
                name: 'IBM ThinkPad 600E',
                slug: 'ibm-thinkpad-600e',
                description: 'Laptop clásica de IBM con procesador Pentium II y Windows 98. Incluye trackpoint rojo característico.',
                price: 299.99,
                originalPrice: 399.99,
                year: 1998,
                manufacturer: 'IBM',
                stock: 3,
                featured: true,
                images: ['/images/thinkpad-600e.jpg'],
                specifications: {
                    cpu: 'Intel Pentium II 366MHz',
                    ram: '128MB SDRAM',
                    storage: '6GB HDD',
                    display: '13.3" TFT 800x600',
                    os: 'Windows 98 SE',
                    ports: 'PS/2, Serial, Parallel, USB',
                },
                categoryId: categories[0].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'compaq-presario-5000' },
            update: {},
            create: {
                name: 'Compaq Presario 5000',
                slug: 'compaq-presario-5000',
                description: 'Torre de escritorio clásica con Pentium III y Windows 2000 Professional.',
                price: 179.99,
                originalPrice: 249.99,
                year: 2000,
                manufacturer: 'Compaq',
                stock: 4,
                featured: true,
                images: ['/images/presario-5000.jpg'],
                specifications: {
                    cpu: 'Intel Pentium III 733MHz',
                    ram: '256MB SDRAM',
                    storage: '20GB HDD',
                    optical: 'CD-ROM 48x',
                    os: 'Windows 2000 Professional',
                    expansion: '3x PCI, 1x AGP',
                },
                categoryId: categories[0].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'dell-dimension-4600' },
            update: {},
            create: {
                name: 'Dell Dimension 4600',
                slug: 'dell-dimension-4600',
                description: 'Computadora de escritorio Dell con Pentium 4 HT y Windows XP.',
                price: 199.99,
                originalPrice: 279.99,
                year: 2003,
                manufacturer: 'Dell',
                stock: 5,
                images: ['/images/dell-4600.jpg'],
                specifications: {
                    cpu: 'Intel Pentium 4 2.8GHz HT',
                    ram: '512MB DDR',
                    storage: '80GB HDD',
                    optical: 'DVD-ROM',
                    os: 'Windows XP Professional',
                    expansion: '4x PCI, 1x AGP 8x',
                },
                categoryId: categories[0].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'hp-pavilion-a1000' },
            update: {},
            create: {
                name: 'HP Pavilion a1000',
                slug: 'hp-pavilion-a1000',
                description: 'Torre multimedia con AMD Athlon 64 y Windows XP Media Center.',
                price: 249.99,
                originalPrice: 329.99,
                year: 2005,
                manufacturer: 'HP',
                stock: 3,
                images: ['/images/hp-a1000.jpg'],
                specifications: {
                    cpu: 'AMD Athlon 64 3200+',
                    ram: '512MB DDR',
                    storage: '160GB SATA',
                    optical: 'DVD+/-RW',
                    os: 'Windows XP Media Center',
                    expansion: '3x PCI, 1x PCIe x16',
                },
                categoryId: categories[0].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'gateway-2000-p5-133' },
            update: {},
            create: {
                name: 'Gateway 2000 P5-133',
                slug: 'gateway-2000-p5-133',
                description: 'PC de escritorio clásica con caja vaca manchada característica de Gateway.',
                price: 149.99,
                originalPrice: 199.99,
                year: 1996,
                manufacturer: 'Gateway',
                stock: 2,
                images: ['/images/gateway-p5.jpg'],
                specifications: {
                    cpu: 'Intel Pentium 133MHz',
                    ram: '32MB EDO RAM',
                    storage: '1.6GB HDD',
                    optical: 'CD-ROM 8x',
                    os: 'Windows 95',
                    expansion: '4x ISA, 3x PCI',
                },
                categoryId: categories[0].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'apple-imac-g3-bondi' },
            update: {},
            create: {
                name: 'Apple iMac G3 Bondi Blue',
                slug: 'apple-imac-g3-bondi',
                description: 'El revolucionario iMac G3 en color Bondi Blue que cambió el diseño de computadoras.',
                price: 349.99,
                originalPrice: 449.99,
                year: 1998,
                manufacturer: 'Apple',
                stock: 2,
                featured: true,
                images: ['/images/imac-g3.jpg'],
                specifications: {
                    cpu: 'PowerPC G3 233MHz',
                    ram: '32MB SDRAM',
                    storage: '4GB HDD',
                    display: '15" CRT 1024x768',
                    os: 'Mac OS 8.1',
                    ports: 'USB, Ethernet, Modem',
                },
                categoryId: categories[0].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'packard-bell-legend' },
            update: {},
            create: {
                name: 'Packard Bell Legend 406CD',
                slug: 'packard-bell-legend',
                description: 'PC multimedia familiar con parlantes integrados y software educativo.',
                price: 129.99,
                originalPrice: 169.99,
                year: 1995,
                manufacturer: 'Packard Bell',
                stock: 3,
                images: ['/images/packard-bell.jpg'],
                specifications: {
                    cpu: 'Intel Pentium 75MHz',
                    ram: '16MB RAM',
                    storage: '850MB HDD',
                    optical: 'CD-ROM 4x',
                    os: 'Windows 95',
                    audio: 'Sound Blaster Compatible',
                },
                categoryId: categories[0].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'emachines-etower-500is' },
            update: {},
            create: {
                name: 'eMachines eTower 500is',
                slug: 'emachines-etower-500is',
                description: 'PC económica pero potente de la era del Internet.',
                price: 99.99,
                originalPrice: 139.99,
                year: 1999,
                manufacturer: 'eMachines',
                stock: 6,
                images: ['/images/emachines.jpg'],
                specifications: {
                    cpu: 'Intel Celeron 500MHz',
                    ram: '64MB SDRAM',
                    storage: '10GB HDD',
                    optical: 'CD-ROM 48x',
                    os: 'Windows 98 SE',
                    modem: '56K V.90',
                },
                categoryId: categories[0].id,
            },
        }),

        // === PROCESADORES ===
        prisma.product.upsert({
            where: { slug: 'intel-pentium-3-800mhz' },
            update: {},
            create: {
                name: 'Intel Pentium III 800MHz',
                slug: 'intel-pentium-3-800mhz',
                description: 'Procesador Intel Pentium III Socket 370, perfecto para builds retro.',
                price: 49.99,
                originalPrice: 49.99,
                year: 2000,
                manufacturer: 'Intel',
                stock: 8,
                featured: true,
                images: ['/images/pentium3-800.jpg'],
                specifications: {
                    socket: 'Socket 370',
                    cores: '1',
                    threads: '1',
                    cache: '256KB L2',
                    fsb: '133MHz',
                },
                categoryId: categories[1].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'amd-athlon-xp-2400' },
            update: {},
            create: {
                name: 'AMD Athlon XP 2400+',
                slug: 'amd-athlon-xp-2400',
                description: 'Procesador AMD Athlon XP con tecnologia QuantiSpeed Architecture.',
                price: 54.99,
                originalPrice: 69.99,
                year: 2002,
                manufacturer: 'AMD',
                stock: 6,
                images: ['/images/athlon-xp-2400.jpg'],
                specifications: {
                    socket: 'Socket A (462)',
                    cores: '1',
                    threads: '1',
                    cache: '256KB L2',
                    fsb: '266MHz',
                    clockSpeed: '2.0GHz',
                },
                categoryId: categories[1].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'intel-pentium-4-3ghz' },
            update: {},
            create: {
                name: 'Intel Pentium 4 3.0GHz',
                slug: 'intel-pentium-4-3ghz',
                description: 'Procesador Pentium 4 con Hyper-Threading y Socket 478.',
                price: 59.99,
                originalPrice: 79.99,
                year: 2003,
                manufacturer: 'Intel',
                stock: 9,
                images: ['/images/pentium4-3ghz.jpg'],
                specifications: {
                    socket: 'Socket 478',
                    cores: '1',
                    threads: '2 (Hyper-Threading)',
                    cache: '512KB L2',
                    fsb: '800MHz',
                    clockSpeed: '3.0GHz',
                },
                categoryId: categories[1].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'amd-k6-2-450' },
            update: {},
            create: {
                name: 'AMD K6-2 450MHz',
                slug: 'amd-k6-2-450',
                description: 'Procesador AMD K6-2 con tecnología 3DNow! para gaming retro.',
                price: 29.99,
                originalPrice: 39.99,
                year: 1998,
                manufacturer: 'AMD',
                stock: 12,
                images: ['/images/k6-2.jpg'],
                specifications: {
                    socket: 'Socket 7',
                    cores: '1',
                    threads: '1',
                    cache: '64KB L1',
                    fsb: '100MHz',
                    clockSpeed: '450MHz',
                },
                categoryId: categories[1].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'intel-pentium-mmx-233' },
            update: {},
            create: {
                name: 'Intel Pentium MMX 233MHz',
                slug: 'intel-pentium-mmx-233',
                description: 'El legendario Pentium MMX, perfecto para DOS gaming.',
                price: 34.99,
                originalPrice: 44.99,
                year: 1997,
                manufacturer: 'Intel',
                stock: 7,
                images: ['/images/pentium-mmx.jpg'],
                specifications: {
                    socket: 'Socket 7',
                    cores: '1',
                    threads: '1',
                    cache: '32KB L1',
                    fsb: '66MHz',
                    clockSpeed: '233MHz',
                },
                categoryId: categories[1].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'cyrix-6x86mx-pr233' },
            update: {},
            create: {
                name: 'Cyrix 6x86MX PR233',
                slug: 'cyrix-6x86mx-pr233',
                description: 'Procesador Cyrix alternativo económico para Socket 7.',
                price: 19.99,
                originalPrice: 29.99,
                year: 1997,
                manufacturer: 'Cyrix',
                stock: 5,
                images: ['/images/cyrix-6x86.jpg'],
                specifications: {
                    socket: 'Socket 7',
                    cores: '1',
                    threads: '1',
                    cache: '64KB L1',
                    fsb: '75MHz',
                    clockSpeed: '187MHz',
                },
                categoryId: categories[1].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'amd-duron-900' },
            update: {},
            create: {
                name: 'AMD Duron 900MHz',
                slug: 'amd-duron-900',
                description: 'Procesador económico AMD Duron para sistemas de entrada.',
                price: 24.99,
                originalPrice: 34.99,
                year: 2001,
                manufacturer: 'AMD',
                stock: 10,
                images: ['/images/duron-900.jpg'],
                specifications: {
                    socket: 'Socket A (462)',
                    cores: '1',
                    threads: '1',
                    cache: '64KB L2',
                    fsb: '200MHz',
                    clockSpeed: '900MHz',
                },
                categoryId: categories[1].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'intel-celeron-300a' },
            update: {},
            create: {
                name: 'Intel Celeron 300A',
                slug: 'intel-celeron-300a',
                description: 'El famoso Celeron 300A, legendario por su overclock a 450MHz.',
                price: 39.99,
                originalPrice: 49.99,
                year: 1998,
                manufacturer: 'Intel',
                stock: 4,
                featured: true,
                images: ['/images/celeron-300a.jpg'],
                specifications: {
                    socket: 'Slot 1 / Socket 370',
                    cores: '1',
                    threads: '1',
                    cache: '128KB L2',
                    fsb: '66MHz',
                    clockSpeed: '300MHz',
                },
                categoryId: categories[1].id,
            },
        }),

        // === MEMORIAS RAM ===
        prisma.product.upsert({
            where: { slug: 'kingston-128mb-pc133' },
            update: {},
            create: {
                name: 'Kingston 128MB PC133 SDRAM',
                slug: 'kingston-128mb-pc133',
                description: 'Módulo de memoria SDRAM de 128MB para sistemas Socket 370/Slot 1',
                price: 24.99,
                originalPrice: 24.99,
                year: 2000,
                manufacturer: 'Kingston',
                stock: 15,
                images: ['/images/kingston-128mb.jpg'],
                specifications: {
                    capacity: '128MB',
                    type: 'SDRAM DIMM',
                    speed: 'PC133 (133MHz)',
                    pins: '168-pin',
                    voltage: '3.3V',
                },
                categoryId: categories[2].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'corsair-256mb-pc2700' },
            update: {},
            create: {
                name: 'Corsair 256MB PC2700 DDR',
                slug: 'corsair-256mb-pc2700',
                description: 'Memoria DDR de 256MB para sistemas AMD Athlon XP y Pentium 4.',
                price: 29.99,
                originalPrice: 29.99,
                year: 2002,
                manufacturer: 'Corsair',
                stock: 12,
                images: ['/images/corsair-256mb.jpg'],
                specifications: {
                    capacity: '256MB',
                    type: 'DDR SDRAM',
                    speed: 'PC2700 (333MHz)',
                    pins: '184-pin',
                    voltage: '2.5V',
                },
                categoryId: categories[2].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'crucial-512mb-pc3200' },
            update: {},
            create: {
                name: 'Crucial 512MB PC3200 DDR',
                slug: 'crucial-512mb-pc3200',
                description: 'Memoria DDR de 512MB con alta velocidad para gaming retro.',
                price: 34.99,
                originalPrice: 34.99,
                year: 2004,
                manufacturer: 'Crucial',
                stock: 14,
                images: ['/images/crucial-512mb.jpg'],
                specifications: {
                    capacity: '512MB',
                    type: 'DDR SDRAM',
                    speed: 'PC3200 (400MHz)',
                    pins: '184-pin',
                    voltage: '2.5V',
                },
                categoryId: categories[2].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'simm-32mb-edo' },
            update: {},
            create: {
                name: 'SIMM 32MB EDO RAM',
                slug: 'simm-32mb-edo',
                description: 'Módulo SIMM de 32MB EDO para sistemas 486 y Pentium tempranos.',
                price: 19.99,
                originalPrice: 24.99,
                year: 1995,
                manufacturer: 'Generic',
                stock: 8,
                images: ['/images/simm-32mb.jpg'],
                specifications: {
                    capacity: '32MB',
                    type: 'EDO SIMM',
                    speed: '60ns',
                    pins: '72-pin',
                    voltage: '5V',
                },
                categoryId: categories[2].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'kingston-64mb-pc100' },
            update: {},
            create: {
                name: 'Kingston 64MB PC100 SDRAM',
                slug: 'kingston-64mb-pc100',
                description: 'Módulo SDRAM de 64MB para sistemas Pentium II y III.',
                price: 14.99,
                originalPrice: 19.99,
                year: 1998,
                manufacturer: 'Kingston',
                stock: 20,
                images: ['/images/kingston-64mb.jpg'],
                specifications: {
                    capacity: '64MB',
                    type: 'SDRAM DIMM',
                    speed: 'PC100 (100MHz)',
                    pins: '168-pin',
                    voltage: '3.3V',
                },
                categoryId: categories[2].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'samsung-1gb-ddr2' },
            update: {},
            create: {
                name: 'Samsung 1GB DDR2-667',
                slug: 'samsung-1gb-ddr2',
                description: 'Memoria DDR2 de 1GB para sistemas modernos retro.',
                price: 24.99,
                originalPrice: 29.99,
                year: 2006,
                manufacturer: 'Samsung',
                stock: 16,
                images: ['/images/samsung-1gb.jpg'],
                specifications: {
                    capacity: '1GB',
                    type: 'DDR2 SDRAM',
                    speed: 'PC2-5300 (667MHz)',
                    pins: '240-pin',
                    voltage: '1.8V',
                },
                categoryId: categories[2].id,
            },
        }),

        // === MONITORES CRT ===
        prisma.product.upsert({
            where: { slug: 'sony-trinitron-cpd-g220' },
            update: {},
            create: {
                name: 'Sony Trinitron CPD-G220',
                slug: 'sony-trinitron-cpd-g220',
                description: 'Monitor CRT profesional de 19" con resolución máxima de 1600x1200. Perfecto para gaming retro.',
                price: 149.99,
                originalPrice: 199.99,
                year: 2001,
                manufacturer: 'Sony',
                stock: 2,
                featured: true,
                images: ['/images/trinitron-g220.jpg'],
                specifications: {
                    size: '19 pulgadas',
                    resolution: '1600x1200 @ 85Hz',
                    dotPitch: '0.24mm',
                    inputs: 'VGA, BNC',
                    technology: 'Trinitron Aperture Grille',
                },
                categoryId: categories[3].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'viewsonic-p95f' },
            update: {},
            create: {
                name: 'ViewSonic P95f+',
                slug: 'viewsonic-p95f',
                description: 'Monitor CRT de 19 pulgadas con excelente calidad de imagen y tasa de refresco.',
                price: 129.99,
                originalPrice: 159.99,
                year: 2002,
                manufacturer: 'ViewSonic',
                stock: 3,
                images: ['/images/viewsonic-p95f.jpg'],
                specifications: {
                    size: '19 pulgadas',
                    resolution: '1600x1200 @ 85Hz',
                    dotPitch: '0.25mm',
                    inputs: 'VGA D-Sub',
                    refreshRate: 'Max 160Hz @ 640x480',
                },
                categoryId: categories[3].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'samsung-syncmaster-997df' },
            update: {},
            create: {
                name: 'Samsung SyncMaster 997DF',
                slug: 'samsung-syncmaster-997df',
                description: 'Monitor CRT de 19 pulgadas con pantalla plana para reducir reflejos.',
                price: 139.99,
                originalPrice: 179.99,
                year: 2003,
                manufacturer: 'Samsung',
                stock: 2,
                images: ['/images/samsung-997df.jpg'],
                specifications: {
                    size: '19 pulgadas',
                    resolution: '1600x1200 @ 75Hz',
                    dotPitch: '0.24mm',
                    inputs: 'VGA D-Sub',
                    flatScreen: 'Si, pantalla plana',
                },
                categoryId: categories[3].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'dell-p1110' },
            update: {},
            create: {
                name: 'Dell P1110 Trinitron',
                slug: 'dell-p1110',
                description: 'Monitor CRT de 21" con tubo Sony Trinitron, ideal para diseño gráfico.',
                price: 199.99,
                originalPrice: 279.99,
                year: 2000,
                manufacturer: 'Dell',
                stock: 1,
                featured: true,
                images: ['/images/dell-p1110.jpg'],
                specifications: {
                    size: '21 pulgadas',
                    resolution: '1920x1440 @ 75Hz',
                    dotPitch: '0.24mm',
                    inputs: 'VGA, 5x BNC',
                    technology: 'Sony Trinitron',
                },
                categoryId: categories[3].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'nec-multisync-fe991sb' },
            update: {},
            create: {
                name: 'NEC MultiSync FE991SB',
                slug: 'nec-multisync-fe991sb',
                description: 'Monitor CRT de 19" con pantalla plana y excelente reproducción de color.',
                price: 159.99,
                originalPrice: 199.99,
                year: 2002,
                manufacturer: 'NEC',
                stock: 2,
                images: ['/images/nec-fe991sb.jpg'],
                specifications: {
                    size: '19 pulgadas',
                    resolution: '1600x1200 @ 85Hz',
                    dotPitch: '0.25mm',
                    inputs: 'VGA D-Sub',
                    flatScreen: 'Si, pantalla plana',
                },
                categoryId: categories[3].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'compaq-v700' },
            update: {},
            create: {
                name: 'Compaq V700',
                slug: 'compaq-v700',
                description: 'Monitor CRT compacto de 17" perfecto para uso general.',
                price: 79.99,
                originalPrice: 99.99,
                year: 1999,
                manufacturer: 'Compaq',
                stock: 5,
                images: ['/images/compaq-v700.jpg'],
                specifications: {
                    size: '17 pulgadas',
                    resolution: '1280x1024 @ 75Hz',
                    dotPitch: '0.27mm',
                    inputs: 'VGA D-Sub',
                },
                categoryId: categories[3].id,
            },
        }),

        // === TARJETAS GRÁFICAS ===
        prisma.product.upsert({
            where: { slug: '3dfx-voodoo3-3000-agp' },
            update: {},
            create: {
                name: '3dfx Voodoo3 3000 AGP',
                slug: '3dfx-voodoo3-3000-agp',
                description: 'Tarjeta gráfica legendaria de 3dfx. ¡La reina del Glide!',
                price: 89.99,
                originalPrice: 89.99,
                year: 1999,
                manufacturer: '3dfx',
                stock: 5,
                featured: true,
                images: ['/images/voodoo3-3000.jpg'],
                specifications: {
                    memory: '16MB SDRAM',
                    interface: 'AGP 2x/4x',
                    ramdac: '300MHz',
                    maxResolution: '2048x1536',
                    api: 'Glide, OpenGL, Direct3D',
                },
                categoryId: categories[4].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'nvidia-riva-tnt2-ultra' },
            update: {},
            create: {
                name: 'NVIDIA Riva TNT2 Ultra',
                slug: 'nvidia-riva-tnt2-ultra',
                description: 'Tarjeta gráfica de alto rendimiento para la época con 32MB de memoria.',
                price: 64.99,
                originalPrice: 64.99,
                year: 1999,
                manufacturer: 'NVIDIA',
                stock: 7,
                images: ['/images/tnt2-ultra.jpg'],
                specifications: {
                    memory: '32MB SDRAM',
                    interface: 'AGP 2x/4x',
                    ramdac: '350MHz',
                    maxResolution: '2048x1536',
                    api: 'OpenGL, Direct3D',
                },
                categoryId: categories[4].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'ati-radeon-9800-pro' },
            update: {},
            create: {
                name: 'ATI Radeon 9800 Pro',
                slug: 'ati-radeon-9800-pro',
                description: 'Una de las mejores tarjetas gráficas de la era AGP con 128MB de memoria.',
                price: 119.99,
                originalPrice: 149.99,
                year: 2003,
                manufacturer: 'ATI',
                stock: 4,
                featured: true,
                images: ['/images/radeon-9800-pro.jpg'],
                specifications: {
                    memory: '128MB DDR',
                    interface: 'AGP 8x',
                    coreClock: '380MHz',
                    memoryClock: '340MHz',
                    api: 'DirectX 9.0, OpenGL 2.0',
                },
                categoryId: categories[4].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'nvidia-geforce-fx-5900-ultra' },
            update: {},
            create: {
                name: 'NVIDIA GeForce FX 5900 Ultra',
                slug: 'nvidia-geforce-fx-5900-ultra',
                description: 'Tarjeta gráfica de gama alta con 256MB de memoria DDR.',
                price: 99.99,
                originalPrice: 129.99,
                year: 2003,
                manufacturer: 'NVIDIA',
                stock: 5,
                images: ['/images/geforce-fx-5900.jpg'],
                specifications: {
                    memory: '256MB DDR',
                    interface: 'AGP 8x',
                    coreClock: '450MHz',
                    memoryClock: '425MHz',
                    api: 'DirectX 9.0, OpenGL 1.5',
                },
                categoryId: categories[4].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: '3dfx-voodoo2-12mb' },
            update: {},
            create: {
                name: '3dfx Voodoo2 12MB',
                slug: '3dfx-voodoo2-12mb',
                description: 'La legendaria Voodoo2, puede usarse en SLI para máximo rendimiento.',
                price: 79.99,
                originalPrice: 89.99,
                year: 1998,
                manufacturer: '3dfx',
                stock: 3,
                images: ['/images/voodoo2.jpg'],
                specifications: {
                    memory: '12MB EDO',
                    interface: 'PCI',
                    maxResolution: '800x600',
                    api: 'Glide, Direct3D',
                    sli: 'Compatible con SLI',
                },
                categoryId: categories[4].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'nvidia-geforce2-mx400' },
            update: {},
            create: {
                name: 'NVIDIA GeForce2 MX400',
                slug: 'nvidia-geforce2-mx400',
                description: 'Tarjeta gráfica económica pero capaz para juegos de la época.',
                price: 34.99,
                originalPrice: 44.99,
                year: 2001,
                manufacturer: 'NVIDIA',
                stock: 9,
                images: ['/images/geforce2-mx400.jpg'],
                specifications: {
                    memory: '64MB DDR',
                    interface: 'AGP 4x',
                    coreClock: '200MHz',
                    memoryClock: '166MHz',
                    api: 'DirectX 7, OpenGL',
                },
                categoryId: categories[4].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'ati-rage-128-pro' },
            update: {},
            create: {
                name: 'ATI Rage 128 Pro',
                slug: 'ati-rage-128-pro',
                description: 'Tarjeta gráfica 2D/3D con excelente calidad de imagen.',
                price: 29.99,
                originalPrice: 39.99,
                year: 1999,
                manufacturer: 'ATI',
                stock: 6,
                images: ['/images/rage-128-pro.jpg'],
                specifications: {
                    memory: '32MB SDRAM',
                    interface: 'AGP 4x',
                    coreClock: '125MHz',
                    maxResolution: '2048x1536',
                    api: 'DirectX 6, OpenGL',
                },
                categoryId: categories[4].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'matrox-g400-max' },
            update: {},
            create: {
                name: 'Matrox G400 MAX',
                slug: 'matrox-g400-max',
                description: 'Tarjeta gráfica con la mejor calidad 2D de su época.',
                price: 44.99,
                originalPrice: 54.99,
                year: 1999,
                manufacturer: 'Matrox',
                stock: 4,
                images: ['/images/matrox-g400.jpg'],
                specifications: {
                    memory: '32MB SGRAM',
                    interface: 'AGP 4x',
                    dualHead: 'Si, DualHead Display',
                    maxResolution: '2048x1536',
                    api: 'DirectX 6, OpenGL',
                },
                categoryId: categories[4].id,
            },
        }),

        // === DISCOS DUROS ===
        prisma.product.upsert({
            where: { slug: 'western-digital-caviar-40gb' },
            update: {},
            create: {
                name: 'Western Digital Caviar 40GB',
                slug: 'western-digital-caviar-40gb',
                description: 'Disco duro IDE de 40GB con 7200 RPM, perfecto para sistemas retro.',
                price: 39.99,
                originalPrice: 39.99,
                year: 2001,
                manufacturer: 'Western Digital',
                stock: 10,
                images: ['/images/wd-caviar-40gb.jpg'],
                specifications: {
                    capacity: '40GB',
                    interface: 'IDE/PATA',
                    rpm: '7200 RPM',
                    cache: '2MB',
                    formFactor: '3.5 inch',
                },
                categoryId: categories[5].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'seagate-barracuda-80gb' },
            update: {},
            create: {
                name: 'Seagate Barracuda 80GB',
                slug: 'seagate-barracuda-80gb',
                description: 'Disco duro IDE de alta velocidad con 80GB de capacidad.',
                price: 44.99,
                originalPrice: 44.99,
                year: 2002,
                manufacturer: 'Seagate',
                stock: 8,
                images: ['/images/seagate-80gb.jpg'],
                specifications: {
                    capacity: '80GB',
                    interface: 'IDE/PATA',
                    rpm: '7200 RPM',
                    cache: '2MB',
                    formFactor: '3.5 inch',
                },
                categoryId: categories[5].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'maxtor-diamondmax-120gb' },
            update: {},
            create: {
                name: 'Maxtor DiamondMax 120GB',
                slug: 'maxtor-diamondmax-120gb',
                description: 'Disco duro IDE de 120GB con gran capacidad para la época.',
                price: 49.99,
                originalPrice: 49.99,
                year: 2003,
                manufacturer: 'Maxtor',
                stock: 7,
                images: ['/images/maxtor-120gb.jpg'],
                specifications: {
                    capacity: '120GB',
                    interface: 'IDE/PATA',
                    rpm: '7200 RPM',
                    cache: '8MB',
                    formFactor: '3.5 inch',
                },
                categoryId: categories[5].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'quantum-fireball-10gb' },
            update: {},
            create: {
                name: 'Quantum Fireball 10GB',
                slug: 'quantum-fireball-10gb',
                description: 'Disco duro clásico de Quantum para sistemas de los 90s.',
                price: 24.99,
                originalPrice: 29.99,
                year: 1999,
                manufacturer: 'Quantum',
                stock: 6,
                images: ['/images/quantum-10gb.jpg'],
                specifications: {
                    capacity: '10GB',
                    interface: 'IDE/PATA',
                    rpm: '5400 RPM',
                    cache: '512KB',
                    formFactor: '3.5 inch',
                },
                categoryId: categories[5].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'ibm-deskstar-75gxp' },
            update: {},
            create: {
                name: 'IBM Deskstar 75GXP 45GB',
                slug: 'ibm-deskstar-75gxp',
                description: 'Disco duro IBM de alto rendimiento (verificado y funcional).',
                price: 34.99,
                originalPrice: 44.99,
                year: 2000,
                manufacturer: 'IBM',
                stock: 4,
                images: ['/images/deskstar-75gxp.jpg'],
                specifications: {
                    capacity: '45GB',
                    interface: 'IDE/PATA',
                    rpm: '7200 RPM',
                    cache: '2MB',
                    formFactor: '3.5 inch',
                },
                categoryId: categories[5].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'seagate-cheetah-scsi' },
            update: {},
            create: {
                name: 'Seagate Cheetah 36GB SCSI',
                slug: 'seagate-cheetah-scsi',
                description: 'Disco duro SCSI de alto rendimiento para servidores.',
                price: 59.99,
                originalPrice: 79.99,
                year: 2001,
                manufacturer: 'Seagate',
                stock: 3,
                images: ['/images/cheetah-scsi.jpg'],
                specifications: {
                    capacity: '36GB',
                    interface: 'Ultra160 SCSI',
                    rpm: '10000 RPM',
                    cache: '4MB',
                    formFactor: '3.5 inch',
                },
                categoryId: categories[5].id,
            },
        }),

        // === PERIFÉRICOS ===
        prisma.product.upsert({
            where: { slug: 'ibm-model-m-keyboard' },
            update: {},
            create: {
                name: 'IBM Model M Keyboard',
                slug: 'ibm-model-m-keyboard',
                description: 'El legendario teclado mecánico IBM Model M con switches buckling spring.',
                price: 89.99,
                originalPrice: 119.99,
                year: 1989,
                manufacturer: 'IBM',
                stock: 4,
                featured: true,
                images: ['/images/model-m.jpg'],
                specifications: {
                    switches: 'Buckling Spring',
                    layout: 'Full Size 101 keys',
                    connector: 'PS/2 (adaptador incluido)',
                    weight: '2.5kg',
                },
                categoryId: categories[6].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'microsoft-intellimouse-explorer' },
            update: {},
            create: {
                name: 'Microsoft IntelliMouse Explorer 3.0',
                slug: 'microsoft-intellimouse-explorer',
                description: 'Mouse óptico legendario, favorito de gamers profesionales.',
                price: 49.99,
                originalPrice: 59.99,
                year: 2003,
                manufacturer: 'Microsoft',
                stock: 6,
                featured: true,
                images: ['/images/intellimouse.jpg'],
                specifications: {
                    sensor: 'Óptico 400 DPI',
                    buttons: '5 botones',
                    connector: 'USB',
                    polling: '125Hz',
                },
                categoryId: categories[6].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'logitech-mx500' },
            update: {},
            create: {
                name: 'Logitech MX500',
                slug: 'logitech-mx500',
                description: 'Mouse óptico ergonómico de alta precisión.',
                price: 39.99,
                originalPrice: 49.99,
                year: 2002,
                manufacturer: 'Logitech',
                stock: 5,
                images: ['/images/mx500.jpg'],
                specifications: {
                    sensor: 'Óptico 800 DPI',
                    buttons: '8 botones',
                    connector: 'USB',
                    polling: '125Hz',
                },
                categoryId: categories[6].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'dell-quietkey-keyboard' },
            update: {},
            create: {
                name: 'Dell QuietKey Keyboard',
                slug: 'dell-quietkey-keyboard',
                description: 'Teclado de membrana silencioso de Dell, muy cómodo para escribir.',
                price: 19.99,
                originalPrice: 24.99,
                year: 2000,
                manufacturer: 'Dell',
                stock: 12,
                images: ['/images/dell-quietkey.jpg'],
                specifications: {
                    type: 'Membrana',
                    layout: 'Full Size 104 keys',
                    connector: 'PS/2',
                },
                categoryId: categories[6].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'microsoft-serial-mouse' },
            update: {},
            create: {
                name: 'Microsoft Serial Mouse 2.0',
                slug: 'microsoft-serial-mouse',
                description: 'Mouse de bola clásico con conector serial.',
                price: 9.99,
                originalPrice: 14.99,
                year: 1995,
                manufacturer: 'Microsoft',
                stock: 8,
                images: ['/images/serial-mouse.jpg'],
                specifications: {
                    type: 'Mecánico (bola)',
                    buttons: '2 botones',
                    connector: 'Serial DB9',
                },
                categoryId: categories[6].id,
            },
        }),

        // === TARJETAS DE SONIDO ===
        prisma.product.upsert({
            where: { slug: 'creative-soundblaster-live' },
            update: {},
            create: {
                name: 'Creative Sound Blaster Live!',
                slug: 'creative-soundblaster-live',
                description: 'Tarjeta de sonido con chip EMU10K1 y soporte EAX.',
                price: 34.99,
                originalPrice: 44.99,
                year: 1998,
                manufacturer: 'Creative',
                stock: 7,
                featured: true,
                images: ['/images/sb-live.jpg'],
                specifications: {
                    chip: 'EMU10K1',
                    channels: '4.1 (5.1 con expansión)',
                    interface: 'PCI',
                    sampleRate: '48kHz',
                    eax: 'EAX 1.0 y 2.0',
                },
                categoryId: categories[7].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'creative-awe64-gold' },
            update: {},
            create: {
                name: 'Creative AWE64 Gold',
                slug: 'creative-awe64-gold',
                description: 'Tarjeta ISA con síntesis wavetable de alta calidad.',
                price: 49.99,
                originalPrice: 59.99,
                year: 1996,
                manufacturer: 'Creative',
                stock: 3,
                images: ['/images/awe64-gold.jpg'],
                specifications: {
                    chip: 'EMU8000',
                    wavetable: '4MB ROM + 4MB RAM',
                    interface: 'ISA',
                    midi: 'MPU-401 compatible',
                },
                categoryId: categories[7].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'sound-blaster-16' },
            update: {},
            create: {
                name: 'Sound Blaster 16',
                slug: 'sound-blaster-16',
                description: 'La tarjeta de sonido clásica para DOS gaming.',
                price: 39.99,
                originalPrice: 49.99,
                year: 1992,
                manufacturer: 'Creative',
                stock: 5,
                images: ['/images/sb16.jpg'],
                specifications: {
                    dac: '16-bit',
                    interface: 'ISA',
                    opl: 'OPL3 FM Synthesis',
                    midi: 'MPU-401 compatible',
                },
                categoryId: categories[7].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'creative-audigy-2' },
            update: {},
            create: {
                name: 'Creative Audigy 2 ZS',
                slug: 'creative-audigy-2',
                description: 'Tarjeta de sonido de alta fidelidad con soporte 7.1.',
                price: 44.99,
                originalPrice: 54.99,
                year: 2003,
                manufacturer: 'Creative',
                stock: 6,
                images: ['/images/audigy2.jpg'],
                specifications: {
                    chip: 'CA0102',
                    channels: '7.1',
                    interface: 'PCI',
                    sampleRate: '192kHz',
                    eax: 'EAX Advanced HD',
                },
                categoryId: categories[7].id,
            },
        }),
        prisma.product.upsert({
            where: { slug: 'gravis-ultrasound' },
            update: {},
            create: {
                name: 'Gravis UltraSound MAX',
                slug: 'gravis-ultrasound',
                description: 'Tarjeta de sonido legendaria para demos y MOD trackers.',
                price: 79.99,
                originalPrice: 99.99,
                year: 1994,
                manufacturer: 'Gravis',
                stock: 2,
                images: ['/images/gus-max.jpg'],
                specifications: {
                    wavetable: '1MB RAM (expandible)',
                    channels: '32 voces',
                    interface: 'ISA',
                    codec: 'CS4231',
                },
                categoryId: categories[7].id,
            },
        }),
    ]);

    console.log(`✅ Created ${products.length} products`);
    console.log('🎉 Seeding completed!');
}

main()
    .catch((e) => {
        console.error('❌ Error seeding database:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
